apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-tguc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-tguc
    app.kubernetes.io/part-of: ci1t-830-0048-app
  name: devfile-sample-tguc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-tguc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-tguc
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0048-tenant/ci1t-830-0048-app/devfile-sample-tguc@sha256:dbb73dd1e08ddd2a5cce0a6c8f7d9a8e8545f58c5feab3abd4b852232a28772f
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
